### ISSUE TITLE
Why tf only one source file!

### ISSUE THREAD

**Issue by MatusGuy** [Localtings/mopm#1]
Wtf!

**Comment by tue8** [comment]
Good luck trying to find all the libraries with the right versions and writing your own makefile!

**Comment by MatusGuy** [comment]
you KNEW i was trying to compile it at version 0.1.0.0

**Comment by tue8** [comment]
pre-built binaries in [releases](https://github.com/Localtings/mopm/releases) :trollface:

**Comment by MatusGuy** [comment]
Yeah I know
